parameters:
  - name: SourceSandbox
    displayName: Soure Salesforce Org
    values:
    - abhilash.gottikadevorg
    - abhilash.gottikaqaorg
  - name: commitMessage
    displayName: Enter Commit Message
resources:
   repositories:
   - repository: SantoshKattiPOCNew
     type: github
     endpoint: GitHubConnection-Santosh
     name:  SantoshKattiPOCNew/SantoshKattiPOCNew
jobs:
- job: Run_Package
  pool:
   name: Hosted Windows 2019 with VS2019
  steps:
    - checkout: SantoshKattiPOCNew
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Agent.BuildDirectory)'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
        
      
  