parameters:
  - name: SourceSandbox
    displayName: Soure Salesforce Org
    values:
    - abhilash.gottikadevorg
    - abhilash.gottikaqaorg
  - name: commitMessage
    displayName: Enter Commit Message
resources:
   repositories:
   - repository: SantoshKattiPOCNew
     type: github
     endpoint: GitHubConnection-Santosh
     name:  SantoshKattiPOCNew/SantoshKattiPOCNew
jobs:
- job: Run_Package
  pool:
   name: Hosted Windows 2019 with VS2019
  steps:
    - checkout: SantoshKattiPOCNew
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Agent.BuildDirectory)'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Ant@1
      displayName: Retrieve Metadata
      inputs:
        buildFile: 'deploy\build.xml'
        options: '-Dsf.password=$(sf.password) -Dsf.username=$(sf.username) -Dsf.serverurl=$(sf.serverurl) -Dsf.maxpoll=$(sf.maxpoll) -Dsf.unpackaged=$(sf.unpackaged)'
        targets: '$(targetname)'
        PublishJUnitResults: false
        javaHomeoption: 'JDKVersion'        
      
  