parameters:
- task: PowerShell@2
  inputs:
    filePath: 'C:\Users\Manyam.Konda\Desktop\Azure\RetrieveMetaData.yml'
  - name: SourceSandbox
    displayName: Soure Salesforce Org
    values:
    - abhilash.gottikadev
    - abhilash.gottikaqa1
  - name: commitMessage
    displayName: Enter Commit Message
jobs:
- job: Run_Package
  pool:
   name: Hosted Windows 2019 with VS2019
  steps:
  - task: PowerShell@2
    displayName: Check Out Branch
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World"
          - task: PowerShell@2
            displayName: Check Out Branch
            inputs:
             targetType: 'inline'
             script: 
              $SourceBranchName = "$(Build.SourceBranch)".Replace('refs/heads/','')
              Write-Output "##vso[task.setvariable variable=SourceBranchName;isOutput=true]$SourceBranchName"
              git checkout $SourceBranchName
  - task: Ant@1
    displayName: Retrieve Metadata
    inputs:
     buildFile: 'deploy\build.xml'
     options: '-Dsf.password=$(sf.password) -Dsf.username=$(sf.username) -Dsf.serverurl=$(sf.serverurl) -Dsf.maxpoll=$(sf.maxpoll) -Dsf.unpackaged=$(sf.unpackaged)'
     targets: '$(targetname)'
     publishJUnitResults: false
     javaHomeoption: 'JDKversion'
  - task: PowerShell@2
    displayName: 'Check In Branch'
    inputs:
     targetType: 'inline'
     script:
      echo "***Starting copying from Salesforce to Repo***"
      git config --local user.email $(Build.RequestedForEmail)
      git config --local user.name "$(Build.RequestedFor)"
      git config --local http.extraheader "AUTHORIZATION:bearer $(System.AccessToken)"
      git add.
      git comit -m "${{ parameters.CommitMessage}}"
      git push origin HEAD:$(SourceBranchName)
      echo "*** All Salesforce Metadata Extract are copied Successfull***"